name: 'Claude Marketplace Sync'
description: 'Sync plugins from multiple Claude Code marketplaces into a single marketplace'
author: 'Ralph Bean'

branding:
  icon: 'download-cloud'
  color: 'blue'

inputs:
  config-path:
    description: 'Path to sync configuration file'
    required: false
    default: '.sync-config.json'
  output-path:
    description: 'Path to output marketplace.json file'
    required: false
    default: '.claude-plugin/marketplace.json'
  verbose:
    description: 'Enable verbose logging'
    required: false
    default: 'false'

outputs:
  plugins-count:
    description: 'Number of plugins synced'
    value: ${{ steps.sync.outputs.plugins-count }}
  marketplaces-processed:
    description: 'Number of marketplaces processed'
    value: ${{ steps.sync.outputs.marketplaces-processed }}

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Run marketplace sync
      id: sync
      shell: bash
      run: |
        # Determine verbose flag
        if [[ "${{ inputs.verbose }}" == "true" ]]; then
          VERBOSE_FLAG="--verbose"
        else
          VERBOSE_FLAG=""
        fi

        # Get action path and normalize
        ACTION_PATH="${{ github.action_path }}"
        # Remove trailing slash if present
        ACTION_PATH="${ACTION_PATH%/}"

        # Run the sync script and capture output
        SYNC_OUTPUT=$(python3 "${ACTION_PATH}/sync-marketplaces.py" \
          --config "${{ inputs.config-path }}" \
          --output "${{ inputs.output-path }}" \
          $VERBOSE_FLAG 2>&1)

        EXIT_CODE=$?

        # Display output
        echo "$SYNC_OUTPUT"

        # Exit if sync failed
        if [ $EXIT_CODE -ne 0 ]; then
          echo "::error::Marketplace sync failed"
          exit $EXIT_CODE
        fi

        # Parse output for plugin count
        PLUGINS_COUNT=$(echo "$SYNC_OUTPUT" | grep "Total plugins:" | sed -E 's/.*Total plugins: ([0-9]+).*/\1/')
        if [ -z "$PLUGINS_COUNT" ]; then
          PLUGINS_COUNT="0"
        fi

        # Parse output for marketplaces processed
        MARKETPLACES_COUNT=$(echo "$SYNC_OUTPUT" | grep "Total marketplaces processed:" | sed -E 's/.*Total marketplaces processed: ([0-9]+).*/\1/')
        if [ -z "$MARKETPLACES_COUNT" ]; then
          MARKETPLACES_COUNT="0"
        fi

        # Set outputs
        echo "plugins-count=$PLUGINS_COUNT" >> $GITHUB_OUTPUT
        echo "marketplaces-processed=$MARKETPLACES_COUNT" >> $GITHUB_OUTPUT

        # Display results
        echo "::notice::Synced $PLUGINS_COUNT plugins from $MARKETPLACES_COUNT marketplaces"
